'use strict';
const D=window.STUDY,F=window.ReviewFeedback,$=id=>document.getElementById(id),params=new URLSearchParams(location.search);
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function shuffle(list){const a=[...list];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a;}
const TOPIC_LABELS={'1':'Why Government?','2':'Law & Codification','3':'Who Rules?','4':'Government in Action','5':'Road to Self-Rule','5x':'Toward Independence','6':'Big Ideas About Government','7':'Declaration of Independence','8':'Articles of Confederation'};
let round=[],at=0,points=0,streak=0,best=0,retried=false,done=false,phase='answer',results=[],order=[],scopeId='planned',lengthValue='all',selectedModule=params.get('module'),roundModule=null,roundScopeId=scopeId;
function topicTitle(id){return TOPIC_LABELS[id]||D.modules.find(m=>m.id===id)?.title||'Review topic';}
function modulesFor(){return D.assessments.planned.modules;}
function allowedModules(){return modulesFor(scopeId);}
function selectedIds(){return selectedModule&&allowedModules().includes(selectedModule)?[selectedModule]:[];}
function pool(){const ids=selectedIds();return D.questions.filter(q=>ids.includes(q.module));}
function setPressed(container,attribute,value){container.querySelectorAll(`[${attribute}]`).forEach(button=>button.setAttribute('aria-pressed',String(button.getAttribute(attribute)===value)));}
function configurePage(){document.title='Midterm Review | American Government';$('reviewKind').textContent='Midterm question practice';$('reviewTitle').textContent='Midterm Review';$('reviewDescription').textContent='Practice every question for one midterm topic, then continue through the remaining topics.';$('midtermReviewNav').setAttribute('aria-current','page');setPressed($('lengthButtons'),'data-length',lengthValue);}
function updateAvailable(){const n=pool().length,limit=lengthValue==='all'?n:Math.min(Number(lengthValue),n);$('available').textContent=lengthValue==='all'?`${n} questions · random order · no repeats`:`${n} available · ${limit} in this round`;}
function configure(target){const ids=allowedModules();selectedModule=ids.includes(target)?target:(ids.includes(selectedModule)?selectedModule:ids[0]);configurePage();$('scopeNote').textContent='Review every topic through the Articles of Confederation.';$('moduleList').innerHTML=ids.map(id=>`<button type="button" data-module="${id}" aria-pressed="${id===selectedModule}">${esc(topicTitle(id))}</button>`).join('');$('moduleList').querySelectorAll('[data-module]').forEach(button=>button.onclick=()=>{selectedModule=button.dataset.module;setPressed($('moduleList'),'data-module',selectedModule);updateAvailable();start();$('question').focus();});updateAvailable();}
function start(){const bank=[...new Map(pool().map(question=>[question.id,question])).values()];if(!bank.length)return;const randomized=shuffle(bank),limit=lengthValue==='all'?randomized.length:Math.min(Number(lengthValue),randomized.length);roundScopeId=scopeId;roundModule=selectedModule;round=randomized.slice(0,limit);at=0;points=0;streak=0;best=0;results=[];$('finish').hidden=true;$('playArea').hidden=false;render();}
function stats(){ $('progressText').textContent=`${at+1} / ${round.length}`;$('points').textContent=points;$('streak').textContent=streak;$('best').textContent=best;$('meter').style.width=`${results.length/round.length*100}%`;}
function render(){window.speechSynthesis?.cancel();retried=false;done=false;phase='answer';const q=round[at];$('questionTag').textContent=`${topicTitle(q.module)} / ${q.type}`;$('question').textContent=q.q;$('source').innerHTML=(q.source?`<blockquote><p>${esc(q.source.text)}</p><a target="_blank" rel="noopener" href="${q.source.url}">${esc(q.source.title)}</a></blockquote>`:'')+(q.comparison?`<p class="callout">${esc(q.comparison)}</p>`:'')+(q.perspective?`<p class="small">Perspective: ${esc(q.perspective)}</p>`:'')+(q.diagram==='federalism'?'<figure class="diagram" aria-label="Authority divided between national and state governments"><div><b>National government</b>Constitutional powers</div><div><b>State governments</b>Constitutional powers</div><figcaption>Authority is divided between levels; some powers are shared.</figcaption></figure>':'');if(q.diagram==='atlantic')$('source').insertAdjacentHTML('beforeend','<figure class="diagram" aria-label="Schematic, not to scale: Britain across the Atlantic from thirteen colonies"><div><b>13 colonies</b>Local assemblies and differing interests</div><div><b>Atlantic Ocean</b>Long-distance communication</div><div><b>Britain</b>Imperial authority</div><figcaption>Schematic relationship; not a geographic map or timeline.</figcaption></figure>');if(q.table)$('source').insertAdjacentHTML('beforeend',`<div class="table-wrap"><table><caption>${esc(q.table.caption)}</caption><thead><tr>${q.table.headers.map(h=>`<th scope="col">${esc(h)}</th>`).join('')}</tr></thead><tbody>${q.table.rows.map(row=>`<tr>${row.map((cell,i)=>i===0?`<th scope="row">${esc(cell)}</th>`:`<td>${esc(cell)}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`);$('feedback').textContent=q.kind==='text'?'Explain your thinking, then compare it with a model answer.':'Choose an answer and look for the evidence.';$('followup').innerHTML='<button class="skip-question" id="skipQuestion" aria-label="Skip this question for now; it will return later"><span>Skip for now →</span><small>Comes back later</small></button>';$('skipQuestion').onclick=skipQuestion;
if(q.kind==='mc')choices(q.opts,(idx,button)=>{if(done||phase!=='answer')return;if(idx!==q.ans){retry(button,'Look again at the question and the evidence. Which choice addresses the main idea?');return;}if(q.whyChoices){phase='why';$('feedback').textContent='Correct classification. Now choose the evidence that proves it.';$('question').textContent='But why? Which clue supports your answer?';choices(q.whyChoices,(idx,b)=>{if(done)return;if(idx===q.whyAnswer)complete();else retry(b,'Choose the evidence that actually supports the classification.');});}else complete();});
else if(q.kind==='order'){order=shuffle(q.items.map((_,i)=>i));if(order.every((v,i)=>v===i))order.reverse();renderOrder();}
else{ $('response').innerHTML='<label for="written">Your explanation</label><textarea id="written" placeholder="State an idea and support it with an example…"></textarea><div class="actions"><button class="primary" id="compare">Compare with model</button><button id="hint">Word bank</button></div><p id="wordBank" class="callout" hidden></p>';$('hint').onclick=()=>{$('wordBank').hidden=!$('wordBank').hidden;$('wordBank').textContent=(q.check||[]).map(x=>x.label).join(' · ')||q.concept;};$('compare').onclick=()=>{if(!$('written').value.trim()){$('feedback').textContent='Write an idea first. The word bank can help you start.';return;}$('compare').disabled=true;$('written').readOnly=true;$('feedback').innerHTML=`<b>Model answer:</b> ${esc(q.a)}<br><br>${esc(q.teach)}<br><br>Compare the meaning and evidence, not just matching words. How close was your explanation?`;$('followup').innerHTML='<button data-grade="100">I explained it</button><button data-grade="50">I had part of it</button><button data-grade="0">I need practice</button>';$('followup').querySelectorAll('button').forEach(b=>b.onclick=()=>complete(Number(b.dataset.grade)));};}stats();}
function choices(options,callback){$('response').innerHTML='<div class="choices" id="choices"></div>';shuffle(options.map((text,idx)=>({text,idx}))).forEach(({text,idx})=>{const b=document.createElement('button');b.textContent=text;b.onclick=()=>callback(idx,b);$('choices').append(b);});}
function retry(button,message){retried=true;streak=0;if(button){button.classList.add('wrong');button.disabled=true;}$('feedback').textContent=message+' Try again; no points are taken away.';stats();}
function skipQuestion(){if(done)return;const [deferred]=round.splice(at,1);round.push(deferred);render();$('feedback').textContent='Skipped for now—the question will return before you finish. '+$('feedback').textContent;$('question').focus();}
function renderOrder(focusIndex){const q=round[at];$('response').innerHTML=`<ol class="order-list">${order.map((id,i)=>`<li><span>${esc(q.items[id])}</span><button data-up="${i}" aria-label="Move ${esc(q.items[id])} earlier" ${i===0?'disabled':''}>↑</button><button data-down="${i}" aria-label="Move ${esc(q.items[id])} later" ${i===order.length-1?'disabled':''}>↓</button></li>`).join('')}</ol><button class="primary" id="checkOrder">Check order</button>`;const move=(i,j)=>{[order[i],order[j]]=[order[j],order[i]];renderOrder(j);};document.querySelectorAll('[data-up]').forEach(b=>b.onclick=()=>move(+b.dataset.up,+b.dataset.up-1));document.querySelectorAll('[data-down]').forEach(b=>b.onclick=()=>move(+b.dataset.down,+b.dataset.down+1));$('checkOrder').onclick=()=>{if(done)return;if(order.every((v,i)=>v===i))complete();else retry(null,q.teach);};if(focusIndex!==undefined){const row=$('response').querySelectorAll('li')[focusIndex];row.querySelector('button:not(:disabled)')?.focus();}}
function complete(selfScore){if(done)return;done=true;const q=round[at],earned=selfScore===undefined?(retried?50:100):selfScore,response=F.next(q.kind,earned);points+=earned;streak=earned===100?streak+1:0;best=Math.max(best,streak);results.push({id:q.id,module:q.module,concept:q.concept,earned});$('response').querySelectorAll('button').forEach(b=>b.disabled=true);$('feedback').innerHTML=`<b>${esc(response)} +${earned} points.</b> ${esc(q.teach)}${q.kind==='text'?`<br><br><b>Model answer:</b> ${esc(q.a)}`:''}`;$('followup').innerHTML=`<button class="primary" id="next">${at===round.length-1?'See results':'Next question'} →</button>`;$('next').onclick=()=>{if(at<round.length-1){at++;render();$('question').focus();}else finish();};stats();}
function finish(){window.speechSynthesis?.cancel();$('playArea').hidden=true;$('finish').hidden=false;const weak=results.filter(r=>r.earned<100),solid=results.filter(r=>r.earned===100),concepts=[...new Set(weak.map(r=>r.concept))],strongConcepts=[...new Set(solid.map(r=>r.concept))].filter(concept=>!concepts.includes(concept)),modules=[...new Set(weak.map(r=>r.module))],ids=modulesFor(roundScopeId),currentIndex=ids.indexOf(roundModule),nextId=ids[(currentIndex+1)%ids.length],wrapped=currentIndex===ids.length-1,nextLabel=topicTitle(nextId);$('finish').innerHTML=`<p class="eyebrow">${esc(topicTitle(roundModule))} complete</p><h2 tabindex="-1" id="finishHeading">Review your results.</h2><p>${points} points · ${solid.length} of ${round.length} correct on the first try · longest streak: ${best}.</p>${strongConcepts.length?`<p><b>You answered these well:</b> ${esc(strongConcepts.join(', '))}.</p>`:''}<p><b>Practice again:</b> ${concepts.length?esc(concepts.join(', ')):'You answered every question correctly on the first try.'}</p>${modules.map(id=>`<div class="result-row"><a href="curriculum.html?module=${id}">Review ${esc(topicTitle(id))} →</a></div>`).join('')}<div class="actions" style="margin-top:20px"><button id="continueTopic" class="primary">${wrapped?'Start over':'Continue'}: ${esc(nextLabel)} →</button><button id="again">Practice this topic again</button>${weak.length?'<button id="missed">Repeat missed questions</button>':''}</div><p class="small muted" style="margin-top:16px">Written responses use your own assessment of the model answer. Results describe this practice round, not a classroom grade.</p>`;$('continueTopic').onclick=()=>{scopeId=roundScopeId;selectedModule=nextId;configure(nextId);start();$('question').focus();};$('again').onclick=()=>{scopeId=roundScopeId;selectedModule=roundModule;configure(roundModule);start();};if(weak.length)$('missed').onclick=()=>{round=shuffle(weak.map(r=>D.questions.find(q=>q.id===r.id)));at=0;points=0;streak=0;best=0;results=[];$('finish').hidden=true;$('playArea').hidden=false;render();};$('finishHeading').focus();}
$('lengthButtons').querySelectorAll('[data-length]').forEach(button=>button.onclick=()=>{lengthValue=button.dataset.length;setPressed($('lengthButtons'),'data-length',lengthValue);updateAvailable();start();$('question').focus();});$('hear').onclick=()=>{if(!('speechSynthesis'in window)||$('playArea').hidden)return;window.speechSynthesis.cancel();const q=round[at];const u=new SpeechSynthesisUtterance([$('question').textContent,q.source?.text||'',q.comparison||''].join('. '));u.rate=.9;window.speechSynthesis.speak(u);};$('stop').onclick=()=>window.speechSynthesis?.cancel();window.addEventListener('pagehide',()=>window.speechSynthesis?.cancel());configure(params.get('module'));start();
